# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SPICAdicionarAmostra.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from SPICmatplotlibclassconstruction import PlotGraph
import time
import threading


class Ui_adicionarAmostra(object):
    def setupUi(self, adicionarAmostra):
        adicionarAmostra.setObjectName("adicionarAmostra")
        adicionarAmostra.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(adicionarAmostra)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelNome = QtWidgets.QLabel(self.centralwidget)
        self.labelNome.setObjectName("labelNome")
        self.campoTituloAmostra = QtWidgets.QLineEdit(self.centralwidget)
        self.campoTituloAmostra.setObjectName("campoTituloAmostra")
        self.horizontalLayout_4.addWidget(self.labelNome)
        self.horizontalLayout_4.addWidget(self.campoTituloAmostra)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelMassa = QtWidgets.QLabel(self.centralwidget)
        self.labelMassa.setObjectName("labelMassa")
        self.campoQuantidade = QtWidgets.QLineEdit(self.centralwidget)
        self.campoQuantidade.setObjectName("campoQuantidade")
        self.horizontalLayout_5.addWidget(self.labelMassa)
        self.horizontalLayout_5.addWidget(self.campoQuantidade)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botaoExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.botaoExcluir.setObjectName("botaoExcluir")
        self.horizontalLayout_2.addWidget(self.botaoExcluir)
        self.listaAmostras = QtWidgets.QListWidget(self.centralwidget)
        self.listaAmostras.setObjectName("listaAmostras")
        self.horizontalLayout_2.addWidget(self.listaAmostras)
        self.botaoAdicionar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoAdicionar.setObjectName("botaoAdicionar")
        self.horizontalLayout_2.addWidget(self.botaoAdicionar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.campoTexto = QtWidgets.QLineEdit(self.centralwidget)
        self.campoTexto.setObjectName("campoTexto")
        self.horizontalLayout.addWidget(self.campoTexto)
        self.botaoProcurar = QtWidgets.QToolButton(self.centralwidget)
        self.botaoProcurar.setObjectName("botaoProcurar")
        self.horizontalLayout.addWidget(self.botaoProcurar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.botaoFinalizar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoFinalizar.setObjectName("botaoFinalizar")
        self.verticalLayout_5.addWidget(self.botaoFinalizar)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        adicionarAmostra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(adicionarAmostra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        adicionarAmostra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(adicionarAmostra)
        self.statusbar.setObjectName("statusbar")
        adicionarAmostra.setStatusBar(self.statusbar)
        self.selecaoAutomatica = QtWidgets.QRadioButton(self.centralwidget)
        
        self.selecaoAutomatica.setObjectName("selecaoAutomatica")
        self.verticalLayout_4.addWidget(self.selecaoAutomatica)
        self.selecaoManual = QtWidgets.QRadioButton(self.centralwidget)
        self.selecaoManual.setObjectName("selecaoManual")
        self.verticalLayout_4.addWidget(self.selecaoManual)
        
        self.botaoExcluir.clicked.connect(self.excluiAmostra)
        self.botaoAdicionar.clicked.connect(self.addAmostra)
        self.botaoProcurar.clicked.connect(self.procuraArquivos)
        
        self.selecaoAutomatica.setChecked(True)
        
        self.tipoSelecao = 2
        
        

        self.retranslateUi(adicionarAmostra)
        QtCore.QMetaObject.connectSlotsByName(adicionarAmostra)

    def retranslateUi(self, adicionarAmostra):
        _translate = QtCore.QCoreApplication.translate
        adicionarAmostra.setWindowTitle(_translate("adicionarAmostra", "Adicionar Amostra - SPIC"))
        self.botaoExcluir.setText(_translate("adicionarAmostra", "Excluir"))
        self.botaoAdicionar.setText(_translate("adicionarAmostra", "Adicionar"))
        self.botaoProcurar.setText(_translate("adicionarAmostra", "..."))
        self.botaoFinalizar.setText(_translate("adicionarAmostra", "Finalizar"))
        self.selecaoAutomatica.setText(_translate("adicionarAmostra", "Se&leção Automática"))
        self.selecaoManual.setText(_translate("adicionarAmostra", "Sele&ção Manual"))
        self.labelNome.setText(_translate("adicionarAmostra", "Nome da Amostra:"))
        self.labelMassa.setText(_translate("adicionarAmostra", "Quantidade (unidade de massa): "))
        
    def ajustaEvento(self,e=threading.Event):
        self.botaoFinalizar.clicked.connect(lambda: self.finalizar(e))
        
        
    def addAmostra(self):
        try:
            if self.selecaoManual.isChecked():
                self.tipoSelecao = 1
            else:   
                self.tipoSelecao = 2
            self.grafico = PlotGraph(self.campoTexto.text(),0,1,1,self.tipoSelecao)
            evt = threading.Event()
            self.grafico.plotar(evt)
            t1 = threading.Thread(target=self.salvaAmostra,args=(evt,))
            t1.start()
        except:
            self.campoTexto.setText("escolha um arquivo compatível")
    
        
    def salvaAmostra(self,e):
        if e.wait():
            self.listaAmostras.addItem(str(self.grafico.piValue) + ', ' + str(self.grafico.pmValue) + ', ' + str(self.grafico.pfValue))
     
    def procuraArquivos(self):
        self.path =  QtWidgets.QFileDialog.getOpenFileName(self, 'Abrir Um Arquivo', '','All Files (*.*)')
        if self.path != ('', ''):
            self.campoTexto.setText(self.path[0])
            
    def excluiAmostra(self):
        self.listaAmostras.takeItem(self.listaAmostras.currentRow())
        
    def finalizar(self,e=threading.Event):
        try:    
            float(self.campoQuantidade.text())
            e.set()
            self.close()
        except:
            
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("Insira um valor de quantidade correto (deve ser numero, com ponto(.) como unidade separadora (Ex: 1.25)")
            msg.setWindowTitle("Erro")
            msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
            retval = msg.exec_()

        
        
            
        
        
        
        
